### ISSUE TITLE
Fiat Punto Evo 

### ISSUE THREAD

**Issue by mevlutsenol** [rumburake/AutoVolume#1]
Hi rumburake,

I examined your code. Good job! Congratulations.

How can I convert canbus informations for Fiat Punto Evo ? I want to display speed, rpm etc. with gauges.

Thanks..

**Comment by mbadea** [comment]
The info is just numbers, they can be decoded only by disassembling and looking at the original code which is obfuscated too. I will try to make an interface so everyone can plugin their code for other models too.

**Comment by rumburake** [comment]
The info is just numbers, they can be decoded only by disassembling and looking at the original code which is obfuscated too.
I will try to make an interface so everyone can plugin their code for other car models.
