### ISSUE TITLE
Max. Volume on door opening

### ISSUE THREAD

**Issue by FogfiRED** [rumburake/AutoVolume#2]
When opening a door with ignition off but key still inserted and RNS is on, the vehicle speed is set to 327 km/h and so the volume is increasing to max. settings. Is it possible to add a variable that with rpm 0 the speed cannot be fast?
![autovolume](https://user-images.githubusercontent.com/5559915/38728989-cb69243a-3f11-11e8-88ec-0d2581789a82.png)

**Comment by mbadea** [comment]
Very interesting, I will have a look!
BTW what car is it? I test on a Skoda Octavia.
Thanks!

**Comment by rumburake** [comment]
Very interesting, I will have a look!
BTW what car is it? Does the app work otherwise?
I can only test on a Skoda Octavia.
Thanks!

**Comment by FogfiRED** [comment]
The app does work otherwise perfectly. Thank you very much for the app!
It is a VW Golf 6.

**Comment by rumburake** [comment]
Great, I'm happy it works!
I did a fix that if the engine is off, speed will be sent to 0 too so you can't get any added volume.
Please check out v1.2.1 and close this if the fix works.

**Comment by FogfiRED** [comment]
Appreciated! Seems to work very well. I'll test it tomorrow again under business day conditions an will give you a note.

**Comment by FogfiRED** [comment]
The fix works fine. Everything is looking good. Thanks again for your fast fix!
