### ISSUE TITLE
Back to life

### ISSUE THREAD

**Issue by MichalSy** [rumburake/AutoVolume#3]
I'd like to bring your project back to life. It would be great if I could ask you a few questions. How exactly did you recognize the information from the Canbus? Is there a logger you used? In the code I found the following place "voodoo incantation starts here" what does that mean and where does the code come from? The next question would be, is it possible to suppress a keystroke and intercept it yourself? I would like to give the keys for the board computer another use. At the moment I can only intercept the keys for multimedia?

Maybe you can give me your contact information so we can communicate more easily.
Maybe in German?! :)

**Comment by rumburake** [comment]
Hi Michal! unfortunately I don't know much German, and I don't have a lot of time; but to better understand how this app was made please look at this [thread on XDA](https://forum.xda-developers.com/android-auto/mtcd-discussion-questions-development/reading-vechicle-sensor-data-android-t3670024) - including F1X's MtcdAutoVolume!
If after reading it you feel you would like to fork the project and have the time to make a generic framework to be extended for other vehicles I will try to answer specific technical questions if you get stuck.
