### ISSUE TITLE
Information about how communicate with CANbus

### ISSUE THREAD

**Issue by gamelaster** [rumburake/AutoVolume#4]
Hello!

Thanks for this project! I want to make my own app for my Android Headunit with PX5 (using Microntek soft), and this is great source of information. Anyway, do you have any tips or notes for making own service? I would highly appreciate that, it would help me a lot (since, reversing and analyzing the decompiled Microntek APKs is very time-consuming, mainly since all variable names are removed).

Thanks

**Comment by rumburake** [comment]
Sorry for such a delayed answer. You are correct, the only way I had is to look at the decompiled sources, with silly arithmethics and no variable names. This is the reason I could only make it work for one car (I had only VW for testing).
